//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.1.1
//     from Assets/Settings/Controller.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controller : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controller()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controller"",
    ""maps"": [
        {
            ""name"": ""Gamepad"",
            ""id"": ""207f4a23-c2d7-4cf0-a3cc-5d99e26c5636"",
            ""actions"": [
                {
                    ""name"": ""Cam Vertical"",
                    ""type"": ""Value"",
                    ""id"": ""a7ee3cc7-a2a5-4d6f-af4c-5c934384994b"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Cam Horizontal"",
                    ""type"": ""Value"",
                    ""id"": ""4e98ee38-0bf5-4a94-aa5a-262b6c7f9a07"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""6dcdec06-d787-4a7b-afa8-ab4a53ab88e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""Button"",
                    ""id"": ""e2ecc1bb-fac1-4812-9687-fe07ef855cfe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Run"",
                    ""type"": ""Button"",
                    ""id"": ""7e64be53-a0f6-4e41-9bc8-02ef2e04115b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Horizontal"",
                    ""type"": ""Value"",
                    ""id"": ""09888f07-105a-403b-9406-344a63ad3eae"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Vertical"",
                    ""type"": ""Value"",
                    ""id"": ""16c45b21-e775-4b99-b62a-9c90908e476b"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Flashlight"",
                    ""type"": ""Button"",
                    ""id"": ""38a2b8ba-8fce-4f5c-a749-b7308b927779"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""Button"",
                    ""id"": ""54474c75-b116-45f7-b067-d0c8c57a49ad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hold"",
                    ""type"": ""Button"",
                    ""id"": ""6855fdd7-ec1f-46f0-a9b0-1a5d6b8eca70"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""eb783a19-2969-4ee8-a860-55edad397242"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Flash Zoom"",
                    ""type"": ""Button"",
                    ""id"": ""fa185041-f83a-4c3d-981f-e04e59808451"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9ba8792f-5c19-4679-ba69-0ee618b0b02c"",
                    ""path"": ""<HID::Performance Designed Products Wired Fight Pad Pro for Nintendo Switch>/rz"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cam Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82155a2b-5456-47bf-9999-f53f11c1a0b9"",
                    ""path"": ""<Gamepad>/rightStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cam Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fea3e60f-2a14-482b-85e1-a2747daed0ff"",
                    ""path"": ""<DualShockGamepad>/rightStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cam Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ab190156-9632-4de1-bc7a-9cae33359850"",
                    ""path"": ""<XInputController>/rightStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cam Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""94d102b2-9363-4cca-8551-8f6defd0c7f6"",
                    ""path"": ""<HID::Performance Designed Products Wired Fight Pad Pro for Nintendo Switch>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cam Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8255e78-f72c-4cf0-be2c-06ab1bdfcfb9"",
                    ""path"": ""<Gamepad>/rightStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cam Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da40e900-82ea-4d94-9846-117de7cc1a05"",
                    ""path"": ""<DualShockGamepad>/rightStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cam Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f31aa600-cc1f-47de-941c-eadb0ba5965d"",
                    ""path"": ""<XInputController>/rightStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Cam Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af53f2a1-b13b-435b-9bbc-ce7857cf6987"",
                    ""path"": ""<HID::Performance Designed Products Wired Fight Pad Pro for Nintendo Switch>/button2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b3107589-8f4b-4dc9-8756-200f151e2c2a"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4a6cbdeb-7b2c-462c-8466-a2cef04a8177"",
                    ""path"": ""<DualShockGamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""928ea0fb-4776-4412-b313-ec5088dcabfc"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""659cb06a-2947-4966-bdba-84c27247bc1c"",
                    ""path"": ""<HID::Performance Designed Products Wired Fight Pad Pro for Nintendo Switch>/button3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5353b05d-581d-4414-937c-9033a5dc8c85"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""05038924-4415-4736-897c-95a57c20ff03"",
                    ""path"": ""<DualShockGamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bee8085d-86de-40b8-bedb-18b0409e42dd"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""20a6d357-61cc-47b0-b24e-485461fef6ef"",
                    ""path"": ""<HID::Performance Designed Products Wired Fight Pad Pro for Nintendo Switch>/button4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bffe6eb5-952b-457f-a559-0fcc98885305"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fd5ee862-d244-4e2c-ad7c-eeb06fdce6bf"",
                    ""path"": ""<DualShockGamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8637f9a8-8e18-4752-8d03-7d90aad07108"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Run"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""33f9ff92-2b13-4039-8d76-73c1992085d1"",
                    ""path"": ""<Joystick>/stick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aaba6ebf-cc89-450c-9d21-8c605e145c92"",
                    ""path"": ""<Gamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5dd2c341-9147-4a22-b8b8-e26ea40ddd93"",
                    ""path"": ""<DualShockGamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""da370e26-2557-4caf-b1ad-ee1b4b7d986e"",
                    ""path"": ""<Gamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Horizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a3b80443-50d5-4f5b-a3c5-a35d432342f4"",
                    ""path"": ""<Joystick>/stick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37a8b054-40c8-4d82-b413-48ddbf309310"",
                    ""path"": ""<Gamepad>/leftStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7d3668d3-911d-42f7-9c6c-c80dc15f1986"",
                    ""path"": ""<DualShockGamepad>/leftStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9970a14c-1be8-4d06-a131-6dd61914cfcb"",
                    ""path"": ""<Gamepad>/leftStick/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Vertical"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""551da6a2-8fbb-4627-bf29-cdc5caf2f1e2"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flashlight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2156efc2-d1af-4fa0-b26a-c74a74960983"",
                    ""path"": ""<HID::Performance Designed Products Wired Fight Pad Pro for Nintendo Switch>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flashlight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d4e8206e-4602-482d-ab92-08f9d2666504"",
                    ""path"": ""<DualShockGamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flashlight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""acffdba9-3a3a-4c3e-a107-b082703ba028"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flashlight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e221fa02-02c3-4d50-927a-d85de720d209"",
                    ""path"": ""<HID::Performance Designed Products Wired Fight Pad Pro for Nintendo Switch>/button11"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3561913c-f2f4-4ec1-a02c-4e851b00a667"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""15635d51-d1f0-4486-8b84-54db7b60915b"",
                    ""path"": ""<DualShockGamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""389fbfca-ef63-48f5-ae47-60f54fd730c0"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d8b8ea23-5938-43af-a448-ef684a0269a9"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""94a2e3cc-73ca-49c9-9039-a941df1f6fee"",
                    ""path"": ""<HID::Performance Designed Products Wired Fight Pad Pro for Nintendo Switch>/button12"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e32de05-a13b-452c-b746-6a3cc3fa5e80"",
                    ""path"": ""<DualShockGamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a34e778a-ebee-45f5-811b-5ca83dae54b1"",
                    ""path"": ""<XInputController>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hold"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""808fd335-9a00-46ab-bdf6-c3380b4b23c1"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""315a3e24-839c-42df-b11b-c7467bff2f45"",
                    ""path"": ""<HID::Performance Designed Products Wired Fight Pad Pro for Nintendo Switch>/button5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""063267ab-99e7-4bcc-a02f-d46ea84dac43"",
                    ""path"": ""<HID::Performance Designed Products Wired Fight Pad Pro for Nintendo Switch>/button7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""ea5e33ab-7861-4368-b813-570f07ac5f0c"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""fe3930fa-7279-41de-9506-412aa520281b"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""59bdb58a-05b3-48fc-9f2a-f7334ad704b7"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""80be1e69-db6d-4f9a-a1c5-dfbcd662d9a6"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""b8099efa-a0a1-4f3e-a6c8-9d79eeb68caf"",
                    ""path"": ""<XInputController>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""22612d52-6203-493b-977b-024123006c6c"",
                    ""path"": ""<XInputController>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""f88ee8fb-a28f-47a8-ae9e-1619e4876269"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flash Zoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""71f7be4c-b9e9-42f4-983e-61d3bd96fe14"",
                    ""path"": ""<HID::Performance Designed Products Wired Fight Pad Pro for Nintendo Switch>/button6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flash Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""3695e40d-1d85-49e1-bd47-3fe6a7b99bb6"",
                    ""path"": ""<HID::Performance Designed Products Wired Fight Pad Pro for Nintendo Switch>/button8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flash Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""5fe97ea3-5afd-471e-93c5-3c5bb1deb1e0"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flash Zoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""cc72d356-6aa2-4dfe-a740-75297e45b8e6"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flash Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""0afe6289-8c38-4277-895d-9a898c36f932"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flash Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""ba2e92c9-a493-4549-ac04-5e95053fd80f"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flash Zoom"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""797140fb-eaf8-4b6f-87be-6b2b137675d4"",
                    ""path"": ""<XInputController>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flash Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""eabb4de8-5002-479d-afbd-87890505e8fb"",
                    ""path"": ""<XInputController>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flash Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gamepad
        m_Gamepad = asset.FindActionMap("Gamepad", throwIfNotFound: true);
        m_Gamepad_CamVertical = m_Gamepad.FindAction("Cam Vertical", throwIfNotFound: true);
        m_Gamepad_CamHorizontal = m_Gamepad.FindAction("Cam Horizontal", throwIfNotFound: true);
        m_Gamepad_Jump = m_Gamepad.FindAction("Jump", throwIfNotFound: true);
        m_Gamepad_Click = m_Gamepad.FindAction("Click", throwIfNotFound: true);
        m_Gamepad_Run = m_Gamepad.FindAction("Run", throwIfNotFound: true);
        m_Gamepad_Horizontal = m_Gamepad.FindAction("Horizontal", throwIfNotFound: true);
        m_Gamepad_Vertical = m_Gamepad.FindAction("Vertical", throwIfNotFound: true);
        m_Gamepad_Flashlight = m_Gamepad.FindAction("Flashlight", throwIfNotFound: true);
        m_Gamepad_Crouch = m_Gamepad.FindAction("Crouch", throwIfNotFound: true);
        m_Gamepad_Hold = m_Gamepad.FindAction("Hold", throwIfNotFound: true);
        m_Gamepad_Zoom = m_Gamepad.FindAction("Zoom", throwIfNotFound: true);
        m_Gamepad_FlashZoom = m_Gamepad.FindAction("Flash Zoom", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gamepad
    private readonly InputActionMap m_Gamepad;
    private IGamepadActions m_GamepadActionsCallbackInterface;
    private readonly InputAction m_Gamepad_CamVertical;
    private readonly InputAction m_Gamepad_CamHorizontal;
    private readonly InputAction m_Gamepad_Jump;
    private readonly InputAction m_Gamepad_Click;
    private readonly InputAction m_Gamepad_Run;
    private readonly InputAction m_Gamepad_Horizontal;
    private readonly InputAction m_Gamepad_Vertical;
    private readonly InputAction m_Gamepad_Flashlight;
    private readonly InputAction m_Gamepad_Crouch;
    private readonly InputAction m_Gamepad_Hold;
    private readonly InputAction m_Gamepad_Zoom;
    private readonly InputAction m_Gamepad_FlashZoom;
    public struct GamepadActions
    {
        private @Controller m_Wrapper;
        public GamepadActions(@Controller wrapper) { m_Wrapper = wrapper; }
        public InputAction @CamVertical => m_Wrapper.m_Gamepad_CamVertical;
        public InputAction @CamHorizontal => m_Wrapper.m_Gamepad_CamHorizontal;
        public InputAction @Jump => m_Wrapper.m_Gamepad_Jump;
        public InputAction @Click => m_Wrapper.m_Gamepad_Click;
        public InputAction @Run => m_Wrapper.m_Gamepad_Run;
        public InputAction @Horizontal => m_Wrapper.m_Gamepad_Horizontal;
        public InputAction @Vertical => m_Wrapper.m_Gamepad_Vertical;
        public InputAction @Flashlight => m_Wrapper.m_Gamepad_Flashlight;
        public InputAction @Crouch => m_Wrapper.m_Gamepad_Crouch;
        public InputAction @Hold => m_Wrapper.m_Gamepad_Hold;
        public InputAction @Zoom => m_Wrapper.m_Gamepad_Zoom;
        public InputAction @FlashZoom => m_Wrapper.m_Gamepad_FlashZoom;
        public InputActionMap Get() { return m_Wrapper.m_Gamepad; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GamepadActions set) { return set.Get(); }
        public void SetCallbacks(IGamepadActions instance)
        {
            if (m_Wrapper.m_GamepadActionsCallbackInterface != null)
            {
                @CamVertical.started -= m_Wrapper.m_GamepadActionsCallbackInterface.OnCamVertical;
                @CamVertical.performed -= m_Wrapper.m_GamepadActionsCallbackInterface.OnCamVertical;
                @CamVertical.canceled -= m_Wrapper.m_GamepadActionsCallbackInterface.OnCamVertical;
                @CamHorizontal.started -= m_Wrapper.m_GamepadActionsCallbackInterface.OnCamHorizontal;
                @CamHorizontal.performed -= m_Wrapper.m_GamepadActionsCallbackInterface.OnCamHorizontal;
                @CamHorizontal.canceled -= m_Wrapper.m_GamepadActionsCallbackInterface.OnCamHorizontal;
                @Jump.started -= m_Wrapper.m_GamepadActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_GamepadActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_GamepadActionsCallbackInterface.OnJump;
                @Click.started -= m_Wrapper.m_GamepadActionsCallbackInterface.OnClick;
                @Click.performed -= m_Wrapper.m_GamepadActionsCallbackInterface.OnClick;
                @Click.canceled -= m_Wrapper.m_GamepadActionsCallbackInterface.OnClick;
                @Run.started -= m_Wrapper.m_GamepadActionsCallbackInterface.OnRun;
                @Run.performed -= m_Wrapper.m_GamepadActionsCallbackInterface.OnRun;
                @Run.canceled -= m_Wrapper.m_GamepadActionsCallbackInterface.OnRun;
                @Horizontal.started -= m_Wrapper.m_GamepadActionsCallbackInterface.OnHorizontal;
                @Horizontal.performed -= m_Wrapper.m_GamepadActionsCallbackInterface.OnHorizontal;
                @Horizontal.canceled -= m_Wrapper.m_GamepadActionsCallbackInterface.OnHorizontal;
                @Vertical.started -= m_Wrapper.m_GamepadActionsCallbackInterface.OnVertical;
                @Vertical.performed -= m_Wrapper.m_GamepadActionsCallbackInterface.OnVertical;
                @Vertical.canceled -= m_Wrapper.m_GamepadActionsCallbackInterface.OnVertical;
                @Flashlight.started -= m_Wrapper.m_GamepadActionsCallbackInterface.OnFlashlight;
                @Flashlight.performed -= m_Wrapper.m_GamepadActionsCallbackInterface.OnFlashlight;
                @Flashlight.canceled -= m_Wrapper.m_GamepadActionsCallbackInterface.OnFlashlight;
                @Crouch.started -= m_Wrapper.m_GamepadActionsCallbackInterface.OnCrouch;
                @Crouch.performed -= m_Wrapper.m_GamepadActionsCallbackInterface.OnCrouch;
                @Crouch.canceled -= m_Wrapper.m_GamepadActionsCallbackInterface.OnCrouch;
                @Hold.started -= m_Wrapper.m_GamepadActionsCallbackInterface.OnHold;
                @Hold.performed -= m_Wrapper.m_GamepadActionsCallbackInterface.OnHold;
                @Hold.canceled -= m_Wrapper.m_GamepadActionsCallbackInterface.OnHold;
                @Zoom.started -= m_Wrapper.m_GamepadActionsCallbackInterface.OnZoom;
                @Zoom.performed -= m_Wrapper.m_GamepadActionsCallbackInterface.OnZoom;
                @Zoom.canceled -= m_Wrapper.m_GamepadActionsCallbackInterface.OnZoom;
                @FlashZoom.started -= m_Wrapper.m_GamepadActionsCallbackInterface.OnFlashZoom;
                @FlashZoom.performed -= m_Wrapper.m_GamepadActionsCallbackInterface.OnFlashZoom;
                @FlashZoom.canceled -= m_Wrapper.m_GamepadActionsCallbackInterface.OnFlashZoom;
            }
            m_Wrapper.m_GamepadActionsCallbackInterface = instance;
            if (instance != null)
            {
                @CamVertical.started += instance.OnCamVertical;
                @CamVertical.performed += instance.OnCamVertical;
                @CamVertical.canceled += instance.OnCamVertical;
                @CamHorizontal.started += instance.OnCamHorizontal;
                @CamHorizontal.performed += instance.OnCamHorizontal;
                @CamHorizontal.canceled += instance.OnCamHorizontal;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
                @Run.started += instance.OnRun;
                @Run.performed += instance.OnRun;
                @Run.canceled += instance.OnRun;
                @Horizontal.started += instance.OnHorizontal;
                @Horizontal.performed += instance.OnHorizontal;
                @Horizontal.canceled += instance.OnHorizontal;
                @Vertical.started += instance.OnVertical;
                @Vertical.performed += instance.OnVertical;
                @Vertical.canceled += instance.OnVertical;
                @Flashlight.started += instance.OnFlashlight;
                @Flashlight.performed += instance.OnFlashlight;
                @Flashlight.canceled += instance.OnFlashlight;
                @Crouch.started += instance.OnCrouch;
                @Crouch.performed += instance.OnCrouch;
                @Crouch.canceled += instance.OnCrouch;
                @Hold.started += instance.OnHold;
                @Hold.performed += instance.OnHold;
                @Hold.canceled += instance.OnHold;
                @Zoom.started += instance.OnZoom;
                @Zoom.performed += instance.OnZoom;
                @Zoom.canceled += instance.OnZoom;
                @FlashZoom.started += instance.OnFlashZoom;
                @FlashZoom.performed += instance.OnFlashZoom;
                @FlashZoom.canceled += instance.OnFlashZoom;
            }
        }
    }
    public GamepadActions @Gamepad => new GamepadActions(this);
    public interface IGamepadActions
    {
        void OnCamVertical(InputAction.CallbackContext context);
        void OnCamHorizontal(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnRun(InputAction.CallbackContext context);
        void OnHorizontal(InputAction.CallbackContext context);
        void OnVertical(InputAction.CallbackContext context);
        void OnFlashlight(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnHold(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
        void OnFlashZoom(InputAction.CallbackContext context);
    }
}
